spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1522/XE
    username: hr
    password: hrpw
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect

server:
  port: 9091

api:
  support:
    ms-human-resources-areas:
      url: http://localhost:9092/ms-hr-areas/v1

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
      base-path: /actuator
      cors:
        allowed-origins: true
